### ISSUE TITLE
Doesn't work on multiple monitor setups

### ISSUE THREAD

**Issue by ShizCalev** [Furimanejo/Underwatch-Ultimate#1]
It's basing the detection region off the aspect ratio of monitor # 1, which is not guaranteed to be your primary monitor.

https://github.com/Furimanejo/Underwatch-Ultimate/blob/36e5feeaf376d3e93f1159b5b9c0e785231849cb/computer_vision.py#L23

In my case, monitor 1 is a vertically oriented secondary monitor, resulting in the region being 45% of my primary screen (which is where overwatch actually runs.)

![2023-11-06 22 41 55](https://github.com/Furimanejo/Underwatch-Ultimate/assets/6209658/36c5dd1f-74fd-4b75-96c2-69d146b43daa)
![2023-11-06 22 43 09](https://github.com/Furimanejo/Underwatch-Ultimate/assets/6209658/558a5b3c-ae31-49a2-9227-7d8039dc7ebb)

**Comment by ShizCalev** [comment]
https://github.com/Furimanejo/Underwatch-Ultimate/blob/36e5feeaf376d3e93f1159b5b9c0e785231849cb/computer_vision.py#L23

**Comment by Furimanejo** [comment]
Feature added on version v1.1.0, check the readme for further instructions.

**Comment by ShizCalev** [comment]
This isn't fixed.... The wrong monitor is still being picked...
![2024-02-15 19 52 24](https://github.com/Furimanejo/Underwatch-Ultimate/assets/6209658/95dd987d-2536-4c17-a179-9b2e62d41e55)
